### PR TITLE
Pull request for final docco merge and review 

### PR DESCRIPTION
**Pull request by ashvds**
Creating this so that we can easily request review.
@jsuresh , who else needs to review?

### CODE REVIEW

**Comment by ashvds** [comment]
@jsuresh @timbod7 I've added the features page for review
https://helix-collective.github.io/hx-deploy-tool/docs/userguide/features.html

That being said, it is a little inconsistent in how it deals with links, so there may be multiple commits for fixing broken links.

**Comment by ashvds** [comment]
@jsuresh @timbod7 , finished first architecture diagram,
https://docs.google.com/drawings/d/1VAdFJzxVvXCZMpT_08SN7MdvcPQZfd_bVtnlqMgKGIs/edit?ts=5d5ca76d
please review

**Comment by ashvds** [comment]
@jsuresh @timbod7 , second architecture ready for review 
https://docs.google.com/drawings/d/1p4iMx5n7X2zp0QDERD8FuzC1g_-Vqph9luq6FKA7q-I/edit?ts=5d5cea19
cc @phuzbot

**Comment by ashvds** [comment]
@jsuresh @timbod7 
the first draft of How it works is up. Similar to the help file in many respects.
https://helix-collective.github.io/hx-deploy-tool/docs/userguide/howitworks
cc @phuzbot

**Comment by paul-thompson-helix** [comment]
Hi Ash, re config templating 
I've added a trivial self contained example in the PR https://github.com/helix-collective/hx-deploy-tool/pull/56

**Comment by ashvds** [comment]
@jsuresh @timbod7 , autoscale cookbook is ready for review
https://helix-collective.github.io/hx-deploy-tool/docs/userguide/stepbystepexamples/3-remote-state-example.html
cc @phuzbot

**Comment by paul-thompson-helix** [comment]
https://github.com/helix-collective/hx-deploy-tool/pull/56 has landed
be sure to replace `deployContexts` array with `configSources` object.

`configSources` defaults to `{}` so your existing examples with `deployContexts=[]` should still work but for doco purposes should be updated.

**Comment by ashvds** [comment]
https://helix-collective.github.io/hx-deploy-tool/docs/userguide/index

**Comment by ashvds** [comment]
new index location https://helix-collective.github.io/hx-deploy-tool/docs/

**Comment by ashvds** [comment]
This requires a final commit to point all the links at the correct relative location when being served from /docs/ instead of /.

**Comment by ashvds** [comment]
fixes #51 
fixes #42 
fixes #40

**Comment by ashvds** [comment]
fixes #20

**Comment by ashvds** [comment]
fixes #50 
fixes #48

**Review by paul-thompson-helix — APPROVED** [review]
Approving - I think it would be well worth landing on master as is now.  Fixing remaining minor formatting and fixing of links seems to be blocked on getting it operating under the proper github pages setup/settings.

**Comment by ashvds** [comment]
@paul-thompson-helix , In theory, when pointing to the docs folder, it should be root, so, have removed /docs from the relative links, and will merge now.

**Pull request merged**
